name: Quatt API Tests

on:
  workflow_dispatch:
jobs:
  test:
    environment: Production
    name: "Run tests"
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Installation of related packages
        run: npm ci
      - name: RUN SuperTest API Tests
        run: npm test
      - name: Save html report
        uses: actions/upload-artifact@master
        with:
          name: allure-results
          path: allure-results
