name: Quatt API Tests

on:
  workflow_dispatch:
jobs:
  test:
    environment: Production
    name: "Run tests"
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Installation of related packages
        run: npm ci

      - name: RUN SuperTest API Tests
        run: npm test

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: main
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Upload test report to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Quatt-gorest-test-report
          path: allure-report
